### ISSUE TITLE
求助ModuleNotFoundError: No module named 'coloredlogs'

### ISSUE THREAD

**Issue by JAcccccccccc** [iOSRealRun-cli/iOSRealRun-cli-17#15]
ModuleNotFoundError: No module named 'coloredlogs' 求助：出现这个是哪里有问题

**Comment by JAcccccccccc** [comment]
解决了上面的问题 现在变成这个了 FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml' 但是目录里明明是有这个文件的

**Comment by JAcccccccccc** [comment]
进去改了下目录，也好了，
Your system version is 17.3.1
2024-03-20 23:17:41 JackJins-tx4 __main__[99844] INFO init done
2024-03-20 23:17:41 JackJins-tx4 __main__[99844] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\init\tunnel.py", line 7, in tunnel_proc
    server_rsd = connect.get_serverrsd()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\driver\connect.py", line 49, in get_serverrsd
    return select_device(None)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\25596\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
    raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError
成这样了555

**Comment by Geniucker** [comment]
I'm responding with an English computer with no Chinese input method so excuse me for using English
1. Make sure you've installed itunes which provides driver
2. Try using another usb interface
3. Try to reboot your phone again
I've met similar condition (after enable the developer mode for the first time) as yours and solved it after step 2 and 3

**Comment by JAcccccccccc** [comment]
fine👌 thanks

**Comment by hanyin111** [comment]
> 进去改了下目录，也好了， Your system version is 17.3.1 2024-03-20 23:17:41 JackJins-tx4 **main**[99844] INFO init done 2024-03-20 23:17:41 JackJins-tx4 **main**[99844] INFO starting tunnel Process Process-1: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run self._target(*self._args, **self._kwargs) File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\init\tunnel.py", line 7, in tunnel_proc server_rsd = connect.get_serverrsd() ^^^^^^^^^^^^^^^^^^^^^^^ File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\driver\connect.py", line 49, in get_serverrsd return select_device(None) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\25596\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device raise NoDeviceConnectedError() pymobiledevice3.exceptions.NoDeviceConnectedError 成这样了555

请问你是怎么解决这个问题的？我在更新系统版本之后也这样了呜呜
