### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

### ISSUE THREAD

**Issue by Harrison3-1122** [iOSRealRun-cli/iOSRealRun-cli-17#16]
```
Traceback (most recent call last):
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 172, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 111, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Temporary\iOSRealRun-cli-17-main\main.py", line 93, in <module>
    main()
  File "D:\Documents\Temporary\iOSRealRun-cli-17-main\main.py", line 46, in main
    init.init()
  File "D:\Documents\Temporary\iOSRealRun-cli-17-main\init\init.py", line 22, in init
    lockdown = connect.get_usbmux_lockdownclient()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Temporary\iOSRealRun-cli-17-main\driver\connect.py", line 18, in get_usbmux_lockdownclient
    lockdown = create_using_usbmux()
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\lockdown.py", line 645, in create_using_usbmux
    service = LockdownServiceConnection.create_using_usbmux(serial, port, connection_type=connection_type,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\service_connection.py", line 87, in create_using_usbmux
    target_device = select_device(udid, connection_type=connection_type, usbmux_address=usbmux_address)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 429, in select_device
    for device in list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 415, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 411, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 179, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python\Lib\site-packages\pymobiledevice3\usbmux.py", line 174, in create_usbmux_socket
    raise ConnectionFailedToUsbmuxdError()
pymobiledevice3.exceptions.ConnectionFailedToUsbmuxdError
```

**Comment by Harrison3-1122** [comment]
![image](https://github.com/iOSRealRun/iOSRealRun-cli-17/assets/109954988/a2d026f5-5d3e-4b88-8b57-47ac90ed1089)
此方法已尝试
