### ISSUE TITLE
Process Process-1:

### ISSUE THREAD

**Issue by hjx39** [iOSRealRun-cli/iOSRealRun-cli-17#39]
Your system version is 17.4.1
2024-05-01 00:51:20 H __main__[6044] INFO init done
2024-05-01 00:51:20 H __main__[6044] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\client.py", line 95, in connect
    protocol.connect(addr)
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 504, in connect
    self._connect(now=now)
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 1217, in _connect
    self._initialize(self._peer_cid.cid)
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 1373, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\x\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Z\其他\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\Z\其他\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\client.py", line 100, in connect
    protocol.close()
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 52, in close
    self.transmit()
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\asyncio\protocol.py", line 102, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H\AppData\Local\Programs\Python\Python312\Lib\site-packages\qh3\quic\connection.py", line 541, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>

**Comment by Clairegggg** [comment]
I solved this by  **pip install qh3==0.15.1**

**Comment by AnyaReese** [comment]
是不是可以把这段也写在 requirement.txt 里？我为了跑这个脚本用 conda 新建了一个 python 环境，装完依赖之后也遇到了这个问题。
