### ISSUE TITLE
pymobiledevice3.exceptions.NoDeviceConnectedError

### ISSUE THREAD

**Issue by HappyWhite666** [iOSRealRun-cli/iOSRealRun-cli-17#54]
Your system version is 17.4.1
2024-05-25 23:47:54 Administrator __main__[42000] INFO init done
2024-05-25 23:47:54 Administrator __main__[42000] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\gtasm\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\gtasm\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gtasm\Desktop\iOSRealRun-cli-17\init\tunnel.py", line 7, in tunnel_proc
    server_rsd = connect.get_serverrsd()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gtasm\Desktop\iOSRealRun-cli-17\driver\connect.py", line 49, in get_serverrsd
    return select_device(None)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gtasm\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
    raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError

**Comment by Yaoyaolingbro** [comment]
same wrong！ Have you fix it?

**Comment by flamelone** [comment]
应该是数据线没连好？

**Comment by Yaoyaolingbro** [comment]
我试了好几个设备哇，都是这样。驱动和网络接口的问题我都解决了，然后就卡在了这一步上😭

**Comment by HappyWhite666** [comment]
我之前一直没解决这个问题，现在重新打开就可以了，我怀疑是因为我之前用的数据线的问题，可能需要正版的数据线。
