### ISSUE TITLE
<Epoch.INTIAL:0>

### ISSUE THREAD

**Issue by flamelone** [iOSRealRun-cli/iOSRealRun-cli-17#66]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\asyncio\client.py", line 97, in connect
    protocol.connect(addr)
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\asyncio\protocol.py", line 62, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\quic\connection.py", line 529, in connect
    self._connect(now=now)
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\quic\connection.py", line 1244, in _connect
    self._initialize(self._peer_cid.cid)
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\quic\connection.py", line 1407, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\iOSRealRun-cli-17-main\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\iOSRealRun-cli-17-main\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
               ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\asyncio\client.py", line 102, in connect
    protocol.close()
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\asyncio\protocol.py", line 54, in close
    self.transmit()
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\asyncio\protocol.py", line 104, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86188\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\qh3\quic\connection.py", line 566, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>

**Comment by ChenxuKwok** [comment]
please try to uninstall current qh3 and install qh3==0.15.1, higher version caused this error

**Comment by jiwei667** [comment]
> please try to uninstall current qh3 and install qh3==0.15.1, higher version caused this error

可以更新打包一个软件吗

**Comment by ChenxuKwok** [comment]
你好，如果您使用的是windows电脑，可以按照以下步骤：
・ 同时按下win+R，输入cmd并回车
・ 在一个新打开的黑框框窗口里面输入以下命令
pip uninstall qh3
・ 等待完成之后
输入
pip install qh3==0.15.1
・ 之后应该就可以正常使用了
如果遇到问题欢迎再给我发邮件~~

________________________________
发件人: jiwei667 ***@***.***>
发送时间: 2024年10月15日 15:51
收件人: iOSRealRun/iOSRealRun-cli-17 ***@***.***>
抄送: ZJUPINEAPPLE ***@***.***>; Comment ***@***.***>
主题: Re: [iOSRealRun/iOSRealRun-cli-17] <Epoch.INTIAL:0> (Issue #66)


please try to uninstall current qh3 and install qh3==0.15.1, higher version caused this error

可以更新打包一个软件吗

―

**Comment by flamelone** [comment]
谢谢，问题解决了
