### ISSUE TITLE
打开了iTunes但是还是noDevicesConnectedError，ipad17.6

### ISSUE THREAD

**Issue by mononihgt** [iOSRealRun-cli/iOSRealRun-cli-17#73]
(env) D:\program\IOSRealRun\iOSRealRun-cli-17>python main.py
Your system version is 17.6.1
2024-11-03 22:27:52 DESKTOP-246UU41 __main__[11584] INFO init done
2024-11-03 22:27:52 DESKTOP-246UU41 __main__[11584] INFO starting tunnel
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1680 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1728 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1920 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 2024 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1812 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1868 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 2072 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1780 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1972 (('::', 5353, 0, 0))): [WinError 87]  参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
2024-11-03 22:27:54 DESKTOP-246UU41 zeroconf[9856] WARNING Error with socket 1820 (('fe80::fa11:74c:3beb:f782', 5353, 0, 55))): [WinError 87] 参数错误。
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 496, in finish_recv
    return ov.getresult()
OSError: [WinError 87] 参数错误。
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\program\IOSRealRun\iOSRealRun-cli-17\init\tunnel.py", line 7, in tunnel_proc
    server_rsd = connect.get_serverrsd()
  File "D:\program\IOSRealRun\iOSRealRun-cli-17\driver\connect.py", line 49, in get_serverrsd
    return select_device(None)
  File "D:\program\IOSRealRun\iOSRealRun-cli-17\env\lib\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
    raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError

**Comment by djgao234** [comment]
Your system version is 18.1
2024-11-18 23:52:26 DESKTOP-PB10ASM __main__[2612] INFO init done
2024-11-18 23:52:26 DESKTOP-PB10ASM __main__[2612] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\init\tunnel.py", line 7, in tunnel_proc
    server_rsd = connect.get_serverrsd()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\driver\connect.py", line 49, in get_serverrsd
    return select_device(None)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
    raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError
