### ISSUE TITLE
重装系统后使用报错

### ISSUE THREAD

**Issue by JAcccccccccc** [iOSRealRun-cli/iOSRealRun-cli-17#74]
Your system version is 17.6.1
2024-11-18 20:11:56 xxxxx __main__[27804] INFO init done
2024-11-18 20:11:56 xxxxx __main__[27804] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\asyncio\client.py", line 97, in connect
    protocol.connect(addr)
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\asyncio\protocol.py", line 62, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\quic\connection.py", line 529, in connect
    self._connect(now=now)
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\quic\connection.py", line 1244, in _connect
    self._initialize(self._peer_cid.cid)
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\quic\connection.py", line 1407, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\iOSFakeRun-Windows (1)\iOSRealRun-cli-17-main\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\asyncio\client.py", line 102, in connect
    protocol.close()
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\asyncio\protocol.py", line 54, in close
    self.transmit()
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\asyncio\protocol.py", line 104, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\qh3\quic\connection.py", line 566, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>

**Comment by JAcccccccccc** [comment]
把qh3那个更新至requirements.txt之后问题解决

**Comment by Gx051101** [comment]
> 把qh3那个更新至requirements.txt之后问题解决
大佬能否细索

**Comment by JAcccccccccc** [comment]
> > 把qh3那个更新至requirements.txt之后问题解决
> > 大佬能否细索

将qh3=0.15.1加入requirement.txt中，以避免由于qh3版本过高问题导致的不能直接在 QuicConfiguration 对象中传递加密证书对象导致的一系列问题<--这是我看到开发者更新的，我试着在那个txt里加一个qh3=0.15.1然后重新安装依赖我的问题就解决了

**Comment by 1823909** [comment]
解锁后连接不上程序  重启无效  ITUNES始终开启  已尝试很多次
