### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by djgao234** [iOSRealRun-cli/iOSRealRun-cli-17#75]

**Comment by djgao234** [comment]
our system version is 18.1
2024-11-18 23:52:26 DESKTOP-PB10ASM main[2612] INFO init done
2024-11-18 23:52:26 DESKTOP-PB10ASM main[2612] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\init\tunnel.py", line 7, in tunnel_proc
server_rsd = connect.get_serverrsd()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\driver\connect.py", line 49, in get_serverrsd
return select_device(None)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError
