### ISSUE TITLE
总结一下常见问题

### ISSUE THREAD

**Issue by KEVIN-G386** [iOSRealRun-cli/iOSRealRun-cli-17#76]
由于作者的号好像被封了，提PR没有用了，恰好我最近身边几位朋友在使用该项目时出现了一些相似问题，故开这个issue总结一下常见的问题，希望对大家有帮助，也希望大佬补充。 大部分内容其实issue里找找也是有的。

1. 手动指定 qh3 版本
最常见的问题，建议clone完项目就运行
```python
 pip install qh3==0.15.1
```
2. NoDeviceConnectedError
也是一个很常见的错误，原因比较多。建议使用原装数据线，同时将itunes 更新到最新版本，并确保串口畅通。
3. python 版本
py3.13 常常会有奇怪的依赖报错，根据身边案例 py 3.9 - 3.12 均能正常使用，同时建议使用虚拟环境
4.  运行 main.py 后在某处卡死，无报错
我也不知道为什么，但是确实在某同学的设备上偶尔发生，重启即可。 ~建议启动前先祈祷~
5. connection timed out
大概率是线的问题，原装线总是会突然断联。

**Comment by djgao234** [comment]
multiprocessing 报错该如何解决
iOS 17.6Beta1

**Comment by djgao234** [comment]
Your system version is 17.6
2024-11-18 23:52:26 DESKTOP-PB10ASM main[2612] INFO init done
2024-11-18 23:52:26 DESKTOP-PB10ASM main[2612] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
self.run()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\init\tunnel.py", line 7, in tunnel_proc
server_rsd = connect.get_serverrsd()
^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\Downloads\iOSRealRun-cli-17-main\iOSRealRun-cli-17-main\driver\connect.py", line 49, in get_serverrsd
return select_device(None)
^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\cli\remote.py", line 159, in select_device
raise NoDeviceConnectedError()
pymobiledevice3.exceptions.NoDeviceConnectedError

**Comment by jiwei667** [comment]
Your system version is 17.3.1
2024-11-23 19:55:42 机尾 __main__[26276] INFO init done
2024-11-23 19:55:42 机尾 __main__[26276] INFO starting tunnel
2024-11-23 19:57:22 机尾 __main__[26276] INFO tunnel started
2024-11-23 19:57:22 机尾 __main__[26276] INFO got route from HNroute.txt
2024-11-23 19:57:22 机尾 __main__[26276] INFO tunnel process terminated
Bye
Traceback (most recent call last):
  File "C:\Users\86153\Desktop\iOSRealRun-cli-17-main\main.py", line 93, in <module>
    main()
  File "C:\Users\86153\Desktop\iOSRealRun-cli-17-main\main.py", line 63, in main
    with RemoteServiceDiscoveryService((address, port)) as rsd:
  File "C:\Users\86153\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 120, in __enter__
    self.connect()
  File "C:\Users\86153\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "C:\Users\86153\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86153\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 865, in create_connection
    raise exceptions[0]
  File "C:\Users\86153\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 850, in create_connection
    sock.connect(sa)
OSError: [WinError 10065] 套接字操作尝试一个无法连接的主机。
这是咋回事

**Comment by AI1379** [comment]
py 3.13的依赖报错是pylzss的报错吗
我也碰到了这个问题 解决方案是安装对应的cpp编译器（windows msbuild/macos clang）然后安装openssl解决
它自己在安装包的时候需要编译一个依赖了openssl的wheel

**Comment by geniucker-dev** [comment]
根据 [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) 的README

> NOTE: Currently, this is only officially supported on macOS & Windows (up to iOS 17.3.1), but fully supported on all platforms starting at iOS 17.4 using the new lockdown tunnel. For windows interaction with iOS 17.0-17.3.1, you'll need to install the additional drivers (we don't provide them)

在iOS 17.4及以上使用了新的更快的lockdown tunnel，治本的方法可能是根据[pymobiledevice3](https://github.com/doronz88/pymobiledevice3)的最新版进行修改。不过目前我没有精力重新读他的新代码，不知道有没有大佬愿意开个fork进行实现/doge

BTW我前几周开了工单试图问GitHub拿回这个组织的所有权

**Comment by ykwcnyali** [comment]
请问针对ios18.2的connectionerror情况有解决方案吗

**Comment by djgao234** [comment]
> 根据 [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) 的README
> 
> 
> 
> > NOTE: Currently, this is only officially supported on macOS & Windows (up to iOS 17.3.1), but fully supported on all platforms starting at iOS 17.4 using the new lockdown tunnel. For windows interaction with iOS 17.0-17.3.1, you'll need to install the additional drivers (we don't provide them)
> 
> 
> 
> 在iOS 17.4及以上使用了新的更快的lockdown tunnel，治本的方法可能是根据[pymobiledevice3](https://github.com/doronz88/pymobiledevice3)的最新版进行修改。不过目前我没有精力重新读他的新代码，不知道有没有大佬愿意开个fork进行实现/doge
> 
> 
> 
> BTW我前几周开了工单试图问GitHub拿回这个组织的所有权

还是以前的iOS17-系统操作简单的多，只需要一个对应版本的开发者镜像以及签名文件就可实现设备调试，iOS17之后越来越麻烦了

**Comment by Ricaey** [comment]
KeyError: <Epoch.INITIAL: 0>

**Comment by Ricaey** [comment]
Process Process-1:
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\qh3\asyncio\client.py", line 97, in connect
    protocol.connect(addr)
  File "D:\Python\Lib\site-packages\qh3\asyncio\protocol.py", line 62, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "D:\Python\Lib\site-packages\qh3\quic\connection.py", line 529, in connect
    self._connect(now=now)
  File "D:\Python\Lib\site-packages\qh3\quic\connection.py", line 1244, in _connect
    self._initialize(self._peer_cid.cid)
  File "D:\Python\Lib\site-packages\qh3\quic\connection.py", line 1407, in _initialize
    raise RuntimeError(  # Defensive: migration from cryptography
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Python\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\iOSRealrun\iOSRealRun-cli-17\init\tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
  File "D:\Python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\iOSRealrun\iOSRealRun-cli-17\driver\connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
  File "D:\Python\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "D:\Python\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "D:\Python\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\qh3\asyncio\client.py", line 102, in connect
    protocol.close()
  File "D:\Python\Lib\site-packages\qh3\asyncio\protocol.py", line 54, in close
    self.transmit()
  File "D:\Python\Lib\site-packages\qh3\asyncio\protocol.py", line 104, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\qh3\quic\connection.py", line 566, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>
佬们有碰到过这个报错吗

**Comment by Undtree** [comment]
请问各位大佬，我这个报错大家有遇到过吗
```text
Your system version is 18.4.1
2025-05-13 15:04:37 LAPTOP-CLOBJJE2 __main__[27576] INFO init done
2025-05-13 15:04:37 LAPTOP-CLOBJJE2 __main__[27576] INFO trying to start tunnel
2025-05-13 15:04:39 LAPTOP-CLOBJJE2 root[8384] INFO Tunnel started
2025-05-13 15:04:39 LAPTOP-CLOBJJE2 root[8384] INFO Usage: python -m pymobiledevice3 lockdown [OPTIONS] COMMAND [ARGS]...
2025-05-13 15:04:39 LAPTOP-CLOBJJE2 root[8384] INFO Try 'python -m pymobiledevice3 lockdown -h' for help.
2025-05-13 15:04:39 LAPTOP-CLOBJJE2 root[8384] INFO Error: No such command 'start-tunnel'.
2025-05-13 15:04:57 LAPTOP-CLOBJJE2 root[27576] ERROR ❌ 隧道建立失败:
2025-05-13 15:04:57 LAPTOP-CLOBJJE2 __main__[27576] INFO got route from ZJGroute1.txt
已开始模拟跑步，速度大约为 3.0 m/s
会无限循环，按 Ctrl+C 退出
请勿直接关闭窗口，否则无法还原正常定位
Traceback (most recent call last):
  File "main.py", line 58, in main
    await run.run(address, port, loc, config.config.v)
  File "F:\iOSRealRun-cli-18\run.py", line 156, in run
    await rsd.connect()
  File "e:\Programs\myenv1\lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 50, in connect
    self.service.connect()
  File "e:\Programs\myenv1\lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 50, in connect
    self.sock = create_connection(self.address)
  File "e:\Programs\myenv1\lib\socket.py", line 799, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "e:\Programs\myenv1\lib\socket.py", line 930, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 63, in main
    logger.debug(f"Is process alive? {process.is_alive()}")
AttributeError: 'NoneType' object has no attribute 'is_alive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 78, in <module>
    asyncio.run(main())
  File "e:\Programs\myenv1\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "e:\Programs\myenv1\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 69, in main
    logger.debug(f"Is process alive? {process.is_alive()}")
AttributeError: 'NoneType' object has no attribute 'is_alive'
```

**Comment by Fakeland-404** [comment]
求pip3怎么下载啊，我copy链接之后该复制在哪里

**Comment by Ricaey** [comment]
> 求pip3怎么下载啊，我copy链接之后该复制在哪里

@Fakeland-404 网上找到pip3 下载指令，在cmd里输入、回车

**Comment by Fakeland-404** [comment]
谢谢！
