### ISSUE TITLE
求求哪个大佬帮帮我，求求了😭，小的不胜感激

### ISSUE THREAD

**Issue by TheNameIsNone** [iOSRealRun-cli/iOSRealRun-cli-17#78]
我是Mac，输入sudo python3 main.py后
Your system version is 17.6.1
2024-12-06 22:39:33 (我的电脑名字）.local __main__[1941] INFO init done
2024-12-06 22:39:33 (我的电脑名字）.local __main__[1941] INFO starting tunnel
Process Process-1:
Traceback (most recent call last):
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/client.py", line 97, in connect
    protocol.connect(addr)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 62, in connect
    self._quic.connect(addr, now=self._loop.time())
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 529, in connect
    self._connect(now=now)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 1244, in _connect
    self._initialize(self._peer_cid.cid)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 1407, in _initialize
    raise RuntimeError(
    ...<4 lines>...
    )
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/init/tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/driver/connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
               ~~~~~~~~~~~~^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
               ~~~~~~~~~~~~~~~~~~~~~~~~~^
            secrets_log_file=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
               ~~~~~~~~~~~~~~~^
            host,
            ^^^^^
    ...<2 lines>...
            create_protocol=RemotePairingQuicTunnel,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as client:
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/client.py", line 102, in connect
    protocol.close()
    ~~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 54, in close
    self.transmit()
    ~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 104, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 566, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>
	
按照下面的帖子我试了换qh3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymobiledevice3 4.16.3 requires qh3<2,>=1.0.0, but you have qh3 0.15.1 which is incompatible.
Successfully installed qh3-0.15.1
重新敲上面的代码还是报错

不开虚拟的报错是
Traceback (most recent call last):
  File "/Users/name/Documents/iOSRealRun-cli-17/main.py", line 11, in <module>
    from init import init
  File "/Users/name/Documents/iOSRealRun-cli-17/init/init.py", line 5, in <module>
    from driver import connect
  File "/Users/name/Documents/iOSRealRun-cli-17/driver/connect.py", line 6, in <module>
    from pymobiledevice3.cli.remote import install_driver_if_required
ImportError: cannot import name 'install_driver_if_required' from 'pymobiledevice3.cli.remote' (/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pymobiledevice3/cli/remote.py)

换成python3.12后的报错
Process Process-1:
Traceback (most recent call last):
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/client.py", line 97, in connect
    protocol.connect(addr)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 62, in connect
    self._quic.connect(addr, now=self._loop.time())
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 529, in connect
    self._connect(now=now)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 1244, in _connect
    self._initialize(self._peer_cid.cid)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 1407, in _initialize
    raise RuntimeError(
    ...<4 lines>...
    )
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/init/tunnel.py", line 8, in tunnel_proc
    asyncio.run(connect.tunnel(server_rsd, queue))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/driver/connect.py", line 53, in tunnel
    async with start_tunnel(rsd, None) as tunnel_result:
               ~~~~~~~~~~~~^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
               ~~~~~~~~~~~~~~~~~~~~~~~~~^
            secrets_log_file=secrets, max_idle_timeout=max_idle_timeout) as tunnel_result:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
               ~~~~~~~~~~~~~~~^
            host,
            ^^^^^
    ...<2 lines>...
            create_protocol=RemotePairingQuicTunnel,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as client:
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/client.py", line 102, in connect
    protocol.close()
    ~~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 54, in close
    self.transmit()
    ~~~~~~~~~~~~~^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/asyncio/protocol.py", line 104, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/Documents/iOSRealRun-cli-17/venv/lib/python3.13/site-packages/qh3/quic/connection.py", line 566, in datagrams_to_send
    crypto = self._cryptos[epoch]
             ~~~~~~~~~~~~~^^^^^^^
KeyError: <Epoch.INITIAL: 0>

**Comment by KEVIN-G386** [comment]
感觉环境不对，虚拟环境的py3.12有换成qh3 0.15 吗

**Comment by TheNameIsNone** [comment]
> 感觉环境不对，虚拟环境的py3.12有换成qh3 0.15 吗

换过了🥹

**Comment by zhangyi-better** [comment]
我也出现了同样的问题 在虚拟环境中换成qh3 0.15后就解决了
